### ISSUE TITLE
panic in `aqua generate`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#218]
```
runtime error: index out of range [-1] 
```

```
  suzuki-shunsuke/matchfile (standard)                                                                  │                                                                                                       
  homeport/dyff (standard)                                                                              │                                                                                                       
  fatedier/frp (standard)                                                                               │                                                                                                       
  terraform-docs (standard)                                                                             │                                                                                                       
  terraform (standard)                                                                                  │                                                                                                       
  suzuki-shunsuke/tfcmt (standard)                                                                      │                                                                                                       
  minamijoyo/tfmigrate (standard)                                                                       │                                                                                                       
  minamijoyo/tfschema (standard)                                                                        │                                                                                                       
  minamijoyo/tfupdate (standard)                                                                        │                                                                                                       
  tfmigrator/cli (standard)                                                                             │                                                                                                       
> tflint (standard)                                                                                     │                                                                                                       
  tfsec (standard)                                                                                      │                                                                                                       
  12/69                                                                                                 │                                                                                                       
> tfpanic: runtime error: index out of range [-1]                                                       └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─

                                                 goroutine 141 [running]:
                                                                         github.com/suzuki-shunsuke/aqua/pkg/controller.(*Controller).Generate.func2(0xc000094c00, 0xc0000b5ce0, 0xc000030358)
                                                                                                                                                                                              	/home/runner/work/aqua/aqua/pkg/controller/generate.go:54 +0x172
                                                github.com/ktr0731/go-fuzzyfinder.(*finder)._drawPreview(0xc000cc05b0)
                                                                                                                      	/home/runner/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.5.0/fuzzyfinder.go:271 +0xbd
 github.com/ktr0731/go-fuzzyfinder.(*finder).initFinder.func1()
                                                               	/home/runner/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.5.0/fuzzyfinder.go:98 +0x2f
                                                                                                                                                        created by time.goFunc
                                                                                                                                                                              	/opt/hostedtoolcache/go/1.17.0/x64/src/time/sleep.go:180 +0x31
```

**Comment by suzuki-shunsuke** [comment]
https://pkg.go.dev/github.com/ktr0731/go-fuzzyfinder#WithPreviewWindow

> If there is no selected item, previewFunc passes -1 to previewFunc.

**Comment by suzuki-shunsuke** [comment]
The bug is caused by #212
